### ISSUE TITLE
Chrome 99 reports that Mess With DNS is a "deceptive site"

### ISSUE THREAD

**Issue by RockyKev** [jvns/mess-with-dns#25] opened 2022-05-08 17:03 UTC
Attempting Experiment 1 or 2 using Chrome Version 99.0.4844.57 (Official Build) (64-bit).

This one: https://i.imgur.com/7J8zxuf.png

The way to bypass is to use the `thisisunsafe` trick. Had to do it a few times as the links redirect.

btw: Absolutely fantastic app.

**Comment by jvns** [comment] 2024-08-16 17:07
I'm closing because I can't reproduce this in the latest version of Chrome, but please reopen if it's still an issue.

**Closed by jvns** 2024-08-16 17:07 UTC
